"""
Chat endpoints with LangGraph Agent execution, multi-model routing, memory enrichment,
dedicated OCR + Moondream visual understanding pipeline, and real-time SSE streaming.
"""

import json
import uuid
import asyncio
from typing import Optional, Dict, Any, List
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from llm.ollama_client import ollama_client
from llm.model_router import model_router
from agents.langgraph_agent import get_langgraph_agent
from memory.memory_manager import memory_manager
from multimodal.multimodal_orchestrator import multimodal_orchestrator
from core.logging import logger
from core.config import settings

router = APIRouter()


class ChatRequest(BaseModel):
    """Chat request payload."""
    message: str = Field(..., description="User message or prompt")
    model: str = Field(default="auto", description="Model name or 'auto' for dynamic routing")
    agent: Optional[str] = Field(default="general", description="Agent slug or 'none'/'direct' for plain chat")
    conversation_id: Optional[str] = Field(None, description="Conversation ID for context retention")
    user_id: Optional[str] = Field(None, description="User ID for RBAC and episodic memory recall")
    task_type: Optional[str] = Field(default="auto", description="Task type classification hint")
    system_prompt: Optional[str] = Field(None, description="Custom system instructions")
    temperature: Optional[float] = Field(None, ge=0.0, le=2.0, description="Sampling temperature")
    max_tokens: Optional[int] = Field(None, ge=1, le=8192, description="Maximum tokens to generate")
    images: Optional[List[str]] = Field(default=None, description="Optional base64 image strings for vision models")


class ChatResponse(BaseModel):
    """Chat response payload."""
    response: str = Field(..., description="Generated text response")
    model_used: str = Field(..., description="Model used for generation")
    task_type: Optional[str] = Field(None, description="Classified task type")
    status: str = Field(default="completed", description="Status of the request")
    agent_used: Optional[str] = Field(default="general", description="Agent used")
    task_id: Optional[str] = Field(None, description="Orchestrator task ID if agentic workflow was run")
    generated_files: Optional[List[Dict[str, Any]]] = Field(default_factory=list, description="Files generated by agent tools")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(default_factory=list, description="Tool calls executed during run")
    tool_executions: Optional[List[Dict[str, Any]]] = Field(default_factory=list, description="Detailed tool executions with stdout and latency")
    ocr: Optional[Dict[str, Any]] = Field(None, description="Exact OCR extraction details")
    vision: Optional[Dict[str, Any]] = Field(None, description="Visual understanding details")
    combined_context: Optional[str] = Field(None, description="Unified OCR + Vision context")


@router.post("/chat", response_model=ChatResponse, summary="Chat with Sovereign AI")
@router.post("/api/chat", response_model=ChatResponse, summary="Chat with Sovereign AI")
async def chat(request: ChatRequest):
    """
    Send a message and get a complete response.
    When images are attached:
    1. Dedicated OCR (PaddleOCR) extracts exact alphanumeric text facts.
    2. Vision Service (Moondream) extracts visual scene understanding.
    3. Outputs are unified into a combined context.
    4. Downstream Agent / LLM reasons over the combined context.
    When no images are attached:
    Regular text-only chat without OCR/Vision invocation.
    """
    try:
        query = request.message.strip()
        has_images = bool(request.images and len(request.images) > 0)

        # -----------------------------------------------------------------
        # MULTIMODAL FLOW: Image attached
        # -----------------------------------------------------------------
        if has_images:
            task_type = "multimodal_inspection"
            primary_image = request.images[0]
            logger.info(f"[CHAT] Multimodal image request received: '{query[:60]}'...")

            # 1. Run Multimodal Orchestration (OCR + Moondream)
            multimodal_result = await multimodal_orchestrator.analyze(
                image_source=primary_image,
                user_prompt=query
            )

            ocr_data = multimodal_result.get("ocr", {})
            vision_data = multimodal_result.get("vision", {})
            unified_context = multimodal_result.get("combined_context", "")

            # 2. Select reasoning model (Chat/Reasoning LLM, not Moondream directly)
            reasoning_model = (
                request.model
                if request.model != "auto"
                else model_router.get_roles().get("chat", settings.OLLAMA_CHAT_MODEL)
            )

            agent_prompt = multimodal_orchestrator.format_agent_prompt(
                unified_context=unified_context,
                user_query=query
            )

            # 3. Downstream Reasoning LLM execution
            messages = [
                {"role": "system", "content": request.system_prompt or "You are an industrial engineering and risk assessment expert."},
                {"role": "user", "content": agent_prompt}
            ]

            options = {}
            if request.temperature is not None:
                options["temperature"] = request.temperature
            if request.max_tokens is not None:
                options["num_predict"] = request.max_tokens

            reply = await ollama_client.chat(model=reasoning_model, messages=messages, options=options if options else None)

            return ChatResponse(
                response=reply,
                model_used=reasoning_model,
                task_type=task_type,
                agent_used=request.agent or "risk_inspector",
                status="completed",
                ocr=ocr_data,
                vision=vision_data,
                combined_context=unified_context
            )

        # -----------------------------------------------------------------
        # REGULAR TEXT CHAT: No images attached
        # -----------------------------------------------------------------
        classification = model_router.classify_task(query)
        task_type = classification["task_type"]
        selected_model = classification["recommended_model"] if request.model == "auto" else request.model

        # Memory Context (Mem0 & Qdrant)
        eff_system_prompt = request.system_prompt or ""
        if request.user_id:
            try:
                memory_ctx = await memory_manager.build_enriched_context(request.user_id, query)
                if memory_ctx:
                    eff_system_prompt = f"{eff_system_prompt}\n\n{memory_ctx}".strip()
            except Exception as mem_err:
                logger.warning(f"Memory retrieval warning: {mem_err}")

        is_agent_mode = bool(request.agent and request.agent.lower() not in ["none", "direct"])

        if is_agent_mode:
            logger.info(f"Executing LangGraph agent '{request.agent}' for text query: {query[:60]}...")
            agent = get_langgraph_agent(
                model=selected_model,
                system_prompt=eff_system_prompt if eff_system_prompt else None,
                temperature=request.temperature,
                max_tokens=request.max_tokens
            )
            result = await agent.execute(query)

            task_id = f"task_{uuid.uuid4().hex[:8]}"
            first_tool = result.get("tool_calls", [{}])[0].get("tool") if result.get("tool_calls") else None
            try:
                await memory_manager.record_task_graph(
                    task_id=task_id,
                    task_type=task_type,
                    tool_name=first_tool
                )
            except Exception as graph_err:
                logger.warning(f"Neo4j record warning: {graph_err}")

            return ChatResponse(
                response=result["final_response"],
                model_used=result["selected_model"],
                task_type=task_type,
                agent_used=request.agent or "general",
                task_id=task_id,
                status="completed",
                generated_files=result.get("generated_files", []),
                tool_calls=result.get("tool_calls", []),
                tool_executions=result.get("tool_executions", [])
            )

        # Direct plain text LLM
        messages = []
        if eff_system_prompt:
            messages.append({"role": "system", "content": eff_system_prompt})
        messages.append({"role": "user", "content": query})

        options = {}
        if request.temperature is not None:
            options["temperature"] = request.temperature
        if request.max_tokens is not None:
            options["num_predict"] = request.max_tokens

        reply = await ollama_client.chat(model=selected_model, messages=messages, options=options if options else None)

        return ChatResponse(
            response=reply,
            model_used=selected_model,
            task_type=task_type,
            agent_used="direct",
            status="completed"
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Chat endpoint error: {e}", exc_info=True)
        raise HTTPException(status_code=502, detail=f"AI service error: {str(e)}")


@router.post("/chat/stream", summary="Stream chat response")
@router.post("/api/chat/stream", summary="Stream chat response")
async def chat_stream(request: ChatRequest):
    """
    Stream a response token-by-token.
    When images are present:
    Emits progressive SSE events for OCR, Vision, Combining, and Reasoning,
    then streams the reasoned assessment.
    """
    try:
        query = request.message.strip()
        has_images = bool(request.images and len(request.images) > 0)

        # -----------------------------------------------------------------
        # MULTIMODAL STREAMING FLOW
        # -----------------------------------------------------------------
        if has_images:
            primary_image = request.images[0]
            reasoning_model = (
                request.model
                if request.model != "auto"
                else model_router.get_roles().get("chat", settings.OLLAMA_CHAT_MODEL)
            )

            async def generate_multimodal():
                try:
                    # 1. Start notification
                    yield f"data: {json.dumps({'event': 'vision:progress', 'stage': 'uploading', 'message': 'Uploading image for multimodal inspection...'}, ensure_ascii=False)}\n\n"
                    await asyncio.sleep(0.05)

                    # 2. Dedicated OCR extraction
                    yield f"data: {json.dumps({'event': 'vision:progress', 'stage': 'ocr', 'message': 'Running OCR (extracting exact text)...'}, ensure_ascii=False)}\n\n"
                    loop = asyncio.get_running_loop()
                    try:
                        ocr_result = await loop.run_in_executor(None, multimodal_orchestrator.ocr.extract_text, primary_image)
                    except Exception as ocr_e:
                        ocr_result = {"success": False, "text": "", "error": str(ocr_e)}

                    # 3. Dedicated Moondream scene understanding
                    yield f"data: {json.dumps({'event': 'vision:progress', 'stage': 'vision', 'message': 'Analyzing visual scene (Moondream)...'}, ensure_ascii=False)}\n\n"
                    try:
                        vision_result = await multimodal_orchestrator.vision.analyze_visual_scene(primary_image)
                    except Exception as vis_e:
                        vision_result = {"success": False, "description": "Vision analysis unavailable.", "error": str(vis_e)}

                    # 4. Combining results
                    yield f"data: {json.dumps({'event': 'vision:progress', 'stage': 'combining', 'message': 'Combining facts and visual context...'}, ensure_ascii=False)}\n\n"
                    unified_context = multimodal_orchestrator.build_unified_context(
                        ocr_text=ocr_result.get("text", ""),
                        vision_description=vision_result.get("description", ""),
                        user_query=query
                    )

                    # Emit combined result event with metadata for UI
                    yield f"data: {json.dumps({'event': 'vision:result', 'ocr': ocr_result, 'vision': vision_result, 'combined_context': unified_context}, ensure_ascii=False)}\n\n"

                    # 5. Generating final reasoning response
                    yield f"data: {json.dumps({'event': 'vision:progress', 'stage': 'reasoning', 'message': 'Generating final risk analysis...'}, ensure_ascii=False)}\n\n"

                    agent_prompt = multimodal_orchestrator.format_agent_prompt(
                        unified_context=unified_context,
                        user_query=query
                    )

                    messages = [
                        {"role": "system", "content": request.system_prompt or "You are an industrial engineering and risk assessment expert."},
                        {"role": "user", "content": agent_prompt}
                    ]

                    stream_options = {}
                    if request.temperature is not None:
                        stream_options["temperature"] = request.temperature
                    if request.max_tokens is not None:
                        stream_options["num_predict"] = request.max_tokens

                    async for token in ollama_client.chat_stream(
                        model=reasoning_model,
                        messages=messages,
                        options=stream_options if stream_options else None
                    ):
                        payload = {"token": token, "content": token}
                        yield f"data: {json.dumps(payload, ensure_ascii=False)}\n\n"

                    # Send completion marker with multimodal metadata
                    yield f"data: {json.dumps({'status': 'completed', 'ocr': ocr_result, 'vision': vision_result}, ensure_ascii=False)}\n\n"
                    logger.info("[CHAT] Multimodal streaming completed successfully.")

                except Exception as e:
                    logger.error(f"Multimodal streaming error: {e}", exc_info=True)
                    yield f"data: {json.dumps({'error': str(e)}, ensure_ascii=False)}\n\n"

            return StreamingResponse(generate_multimodal(), media_type="text/event-stream")

        # -----------------------------------------------------------------
        # REGULAR TEXT STREAMING FLOW (NO OCR OR VISION)
        # -----------------------------------------------------------------
        classification = model_router.classify_task(query)
        task_type = classification["task_type"]
        selected_model = classification["recommended_model"] if request.model == "auto" else request.model

        eff_system_prompt = request.system_prompt or ""
        if request.user_id:
            try:
                memory_ctx = await memory_manager.build_enriched_context(request.user_id, query)
                if memory_ctx:
                    eff_system_prompt = f"{eff_system_prompt}\n\n{memory_ctx}".strip()
            except Exception as mem_err:
                logger.warning(f"Memory context lookup warning: {mem_err}")

        is_agent_mode = bool(request.agent and request.agent.lower() not in ["none", "direct"])

        async def generate_text():
            try:
                yield f"data: {json.dumps({'model': selected_model, 'task_type': task_type, 'status': 'started'}, ensure_ascii=False)}\n\n"

                if is_agent_mode:
                    agent = get_langgraph_agent(
                        model=selected_model,
                        system_prompt=eff_system_prompt if eff_system_prompt else None,
                        temperature=request.temperature,
                        max_tokens=request.max_tokens
                    )
                    async for event in agent.stream(query):
                        yield f"data: {json.dumps(event, ensure_ascii=False)}\n\n"
                else:
                    messages = []
                    if eff_system_prompt:
                        messages.append({"role": "system", "content": eff_system_prompt})
                    messages.append({"role": "user", "content": query})

                    stream_options = {}
                    if request.temperature is not None:
                        stream_options["temperature"] = request.temperature
                    if request.max_tokens is not None:
                        stream_options["num_predict"] = request.max_tokens

                    async for token in ollama_client.chat_stream(
                        model=selected_model,
                        messages=messages,
                        options=stream_options if stream_options else None
                    ):
                        payload = {"token": token, "content": token}
                        yield f"data: {json.dumps(payload, ensure_ascii=False)}\n\n"

                    yield f"data: {json.dumps({'status': 'completed'}, ensure_ascii=False)}\n\n"

                logger.info("Text chat streaming completed successfully.")

            except Exception as e:
                logger.error(f"Streaming generator error: {e}", exc_info=True)
                yield f"data: {json.dumps({'error': str(e)}, ensure_ascii=False)}\n\n"

        return StreamingResponse(generate_text(), media_type="text/event-stream")

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Stream endpoint initialization error: {e}", exc_info=True)
        raise HTTPException(status_code=502, detail=f"Streaming error: {str(e)}")
